#!/bin/sh

if profile=`printcontenv S6_RUNTIME_PROFILE` ; then
  etc="/etc/cont-profile.d/$profile"
else
  etc=/etc
fi

if ! kimeout=`printcontenv S6_KILL_FINISH_MAXTIME` ; then
  kimeout=0
fi

for file in `s6-ls "$etc/cont-finish.d" 2>/dev/null | s6-sort` ; do
  echo "cont-finish: info: running $etc/cont-finish.d/$file" 1>&2
  s6-maximumtime -k "$kimeout" "$etc/cont-finish.d/$file"
done

exit 0
