#!/bin/bash

##
## PARAMS
##

OVERLAY_ROOTFS_PATH=${1:-/overlay-rootfs}
RELEASE_VERSION=${2:-1.4.0}

outputs=(
linux
portable
)

get_packages_with_versions_from_manifest() {
  # manifest
  manifest=$1

  # skarnet versions manifest
  curl -R -L \
      -o /tmp/manifest.txt \
      https://github.com/glerchundi/container-skarnet-builder/releases/download/v$RELEASE_VERSION/$manifest

  # parse manifest into s6 associative array
  versions=()
  while read -r line
  do
      key=`echo "${line}" | cut -d"=" -f1`
      value=`echo "${line}" | cut -d"=" -f2`
      if [[ ! -z "${key}" && ! -z "${value}" ]]; then
          versions+=("${key}-${value}")
      fi
  done < /tmp/manifest.txt

  # delete manifest
  rm /tmp/manifest.txt

  echo ${versions[@]}
}

##
## DOWNLOAD PACKAGES
##

# destination folder
cd /tmp

packages=($(get_packages_with_versions_from_manifest "manifest.txt"))
for package in "${packages[@]}"; do
  file=$package-linux-amd64-bin.tar.gz
  curl -R -L -O https://github.com/glerchundi/container-s6-builder/releases/download/v$RELEASE_VERSION/$file
done

# fix-attrs
curl -R -L -o /tmp/fix-attrs https://github.com/glerchundi/fix-attrs/releases/download/v0.4.0/fix-attrs-0.4.0-linux-amd64

##
## OVERLAYS
##

for output in "${outputs[@]}"
do
  # overlay path
  overlaypath="$OVERLAY_ROOTFS_PATH-$output"

  # create overlay folder
  mkdir -p $overlaypath

  # skarnet versions manifest
  packages=($(get_packages_with_versions_from_manifest "manifest-$output.txt"))

  # install required binaries for this concrete output
  for package in "${packages[@]}"
  do
      tar xvfz /tmp/$package-linux-amd64-bin.tar.gz -C $overlaypath
  done

  # install fix-attrs
  cp /tmp/fix-attrs $overlaypath/usr/bin/fix-attrs

  # fix perms
  chmod +x $overlaypath/init                        \
           $overlaypath/etc/s6/.s6-svscan/finish    \
           $overlaypath/etc/s6/.s6-init/init-stage* \
           $overlaypath/usr/bin/fix-attrs

  ##
  ## DIST!
  ##

  mkdir -p /dist
  tar -zcvf /dist/s6-overlay-$RELEASE_VERSION-$output-amd64.tar.gz -C $overlaypath ./
done
